### ISSUE TITLE
Changing / Disabling background | More of a feature request rather than an issue

### ISSUE THREAD

**Issue by Xishie** [Spekulucius/obsidian-brainhack#5]
I wanted to ask if it would be possible to add an option to the style settings that would allow the user to disable the (I don't know how to describe it) wall-like texture of the background? I like how the theme looks and feels but the background of the window can sometimes look very weird depending on what display I'm using. I hadn't noticed what it looked like until I opened Obsidian on my second monitor and then on the iPad. Other than that, great theme, after trying out the a lot of different ones in the theme store yours was definitely the winner, keep up the good work lad. 

Also I apologize if this is the wrong channel or way to approach you, don't know a lot about Github.

Cheers, Xishie

**Comment by Spekulucius** [comment]
HI, thank you for your feedback, and for using (and liking^^) my theme!

Don't worry, regarding the issue request, you did everything right. I didn't set up a separate channel for issues, so no worries.

I will definitely look into that!

**Comment by Xishie** [comment]
Holy sh.. You're an absolute legend, I wasn't expecting an answer, much less an implementation of my request. Thanks a lot Spek. 

Cheers, Xishie

PS: The moving color gradient on the Title of pages is a pretty neat :)
