### ISSUE TITLE
Hover editor heading icons misaligned

### ISSUE THREAD

**Issue by DutchPete** [Spekulucius/obsidian-brainhack#7]
The Hover Editor is a widely used plug-in, it has been downloaded 250,000 times, which includes my download 😀

When you hover over an internal link and press <kbd>CTRL</kbd>, a pop-up appears that makes editing the original text possible.

This what the heading of the pop-up looks like in other themes:

![grit1](https://github.com/user-attachments/assets/52f6fa3e-3152-4d38-ab9f-ee89a3752c9a)

but this is what it looks like in Brainhack:

![grit2](https://github.com/user-attachments/assets/fa7a5e8f-a72a-4e99-b6f2-d87efc8734ad)

The icons on the right are misaligned.

**Comment by Spekulucius** [comment]
I'll see what I can do about that.

**Comment by DutchPete** [comment]
Thanks for the quick response.
