### ISSUE TITLE
Vibration on edge of table

### ISSUE THREAD

**Issue by DutchPete** [Spekulucius/obsidian-brainhack#8]
When I get to the edge of a table, the image vibrates — see attachment.

https://github.com/user-attachments/assets/664f59b9-b55e-4ba6-ae3b-401a18db98b1

**Comment by Spekulucius** [comment]
Thanks for your feedback (and for still using my theme)!
I'll get onto that, expect a fix in the next 5 minutes :)

**Comment by DutchPete** [comment]
Just to let you know the jitter is gone. Again, thanks for the superfast response.
I have been using Obsidian almost since its inception, well not quite: inception was March 2020, I started using it May 2020.

During the past 4 years I have used many themes, some even more than once, but never felt I had quite found the right one. With your themes I have a fairly strong (being cautious here 😀) that it may be "my" theme, and I am still using as my main theme. But, truth be told, it is early days yet.
